apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: flow
  name: emulator-storage-claim
  namespace: flow
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
